#!/bin/sh
set -e

files_file=$(mktemp -t supacode-pre-commit.XXXXXX)
trap 'rm -f "$files_file"' EXIT

git diff --cached --name-only -z --diff-filter=ACMR -- '*.swift' > "$files_file"
if [ ! -s "$files_file" ]; then
  exit 0
fi

make format FILES_FILE="$files_file"
make lint FILES_FILE="$files_file"

xargs -0 git add -- < "$files_file"
